project/urls.py
from django.contrib import admin  # type: ignore[import-untyped]
from django.urls import include, path  # type: ignore[import-untyped]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

recipes/urls.py
# pylint: disable-msg=C0103
'''Url's from my app recipes'''

from django.urls import path  # type: ignore[import-untyped]

from recipes import views  # type: ignore[no-name-in-module]

app_name = 'recipe'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/<int:id>/', views.recipe, name='recipe'),
]

recipes/models.py
from django.db import models

# Create your models here.

recipes/views.py
'''Views from my app recipes'''

# from django.http import HttpResponse  # type: ignore[import-untyped]
from django.shortcuts import render  # type: ignore[import-untyped]

from utils.recipes.factory import make_recipe


def home(request):
    '''View home'''
    context = {
        'site_title': 'Home',
        'recipes': [make_recipe() for _ in range(9)],
        'is_detail_page': False,
    }
    return render(
        request,
        'recipes/pages/home.html',
        context,
    )


def recipe(request, id):
    '''View home'''
    context = {
        'site_title': 'Recipes',
        'recipe': make_recipe(),
        'is_detail_page': True,
    }
    return render(
        request,
        'recipes/pages/recipe-view.html',
        context,
    )

recipes/templates/recipes/pages/home.html
{% extends "global/base.html" %}
{% block content %}
<div class="main-content container">
        {% for recipe in recipes %}
                {% include "recipes/partials/recipe.html" %}
        {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends "global/base.html" %}
{% block content %}
<div class="main-content-detail container">
        {% include "recipes/partials/recipe.html" %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<div class="developer">
    <p>By Bruna Ballerini</p>
</div>
<div class="powered">
    <a href="https://www.djangoproject.com/">Powered by Django</a>
</div>

recipes/templates/recipes/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/4c97796e98.js" crossorigin="anonymous"></script>
<title>{{site_title}}</title>

recipes/templates/recipes/partials/header.html
<div class="main-header container">
    <h1 class="main-logo">
        <a href="{% url "recipe:home" %}">
            <i class="fa-solid fa-utensils main-icon"></i>
            <span class="main-logo-text">Recipes</span>
            <i class="fa-regular fa-lemon main-icon"></i> 
        </a>
    </h1>
</div>

recipes/templates/recipes/partials/recipe.html
<div class="recipe-item recipe">
    <div class="recipe-cover">
        <a href="{% url "recipe:recipe" 1 %}">
            <img src="{{ recipe.cover.url }}" alt="Food images">
        </a>
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">{{ recipe.title }}</h2>
    </div>
    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {{ recipe.author.first_name }}
            {{ recipe.author.last_name }}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }}
        </span>
        <span class="recipe-author-item">
            <a href="#">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
    </div>
    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i>Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page %}
        <div class="preparation-steps">
            {{ recipe.preparation_steps }}
        </div>
    {% endif %}

    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url "recipe:recipe" 1 %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}
</div>             